name: login_portal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Native splash screen plugin
  flutter_native_splash: ^2.3.11
  pin_code_fields: ^8.0.0

  # State management
  provider: ^6.1.1

  # Icons
  font_awesome_flutter: ^10.6.0

  # iOS style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Your asset added here
  assets:
    - assets/logo.png
    - assets/splash.png
    # If you want entire folder, use this instead:
    # - assets/

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash.png"
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
